// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvabw0HmCArk_cm8PmTNAPSEWaVEeoIjE',
    appId: '1:248452175460:web:febffd8cf6005efdd4b171',
    messagingSenderId: '248452175460',
    projectId: 'sager-857da',
    authDomain: 'sager-857da.firebaseapp.com',
    storageBucket: 'sager-857da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5boSE6TVkWv3Cf-BBE7lG5NsIwdzfo34',
    appId: '1:248452175460:android:18027ad28f71d9f3d4b171',
    messagingSenderId: '248452175460',
    projectId: 'sager-857da',
    storageBucket: 'sager-857da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5dzAxPgMQpY7PSZkhz2oGVn_UJ_UG-ec',
    appId: '1:248452175460:ios:630149e9f1cbd969d4b171',
    messagingSenderId: '248452175460',
    projectId: 'sager-857da',
    storageBucket: 'sager-857da.firebasestorage.app',
    iosBundleId: 'com.example.sager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5dzAxPgMQpY7PSZkhz2oGVn_UJ_UG-ec',
    appId: '1:248452175460:ios:630149e9f1cbd969d4b171',
    messagingSenderId: '248452175460',
    projectId: 'sager-857da',
    storageBucket: 'sager-857da.firebasestorage.app',
    iosBundleId: 'com.example.sager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvabw0HmCArk_cm8PmTNAPSEWaVEeoIjE',
    appId: '1:248452175460:web:6966a35e0515e445d4b171',
    messagingSenderId: '248452175460',
    projectId: 'sager-857da',
    authDomain: 'sager-857da.firebaseapp.com',
    storageBucket: 'sager-857da.firebasestorage.app',
  );
}
